/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IShopMaker, IShopMakerInterface } from "../IShopMaker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "image",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "shopId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "governor",
        type: "address",
      },
    ],
    name: "createShop",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IShopMaker__factory {
  static readonly abi = _abi;
  static createInterface(): IShopMakerInterface {
    return new utils.Interface(_abi) as IShopMakerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IShopMaker {
    return new Contract(address, _abi, signerOrProvider) as IShopMaker;
  }
}
