/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IShopMakerInterface extends utils.Interface {
  contractName: "IShopMaker";
  functions: {
    "createShop(address,string,string,uint256,address)": FunctionFragment;
    "setShopTemplate(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createShop",
    values: [string, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setShopTemplate",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "createShop", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setShopTemplate",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IShopMaker extends BaseContract {
  contractName: "IShopMaker";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IShopMakerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createShop(
      owner: string,
      name: string,
      image: string,
      shopId: BigNumberish,
      governor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setShopTemplate(
      _shopTemplate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createShop(
    owner: string,
    name: string,
    image: string,
    shopId: BigNumberish,
    governor: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setShopTemplate(
    _shopTemplate: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createShop(
      owner: string,
      name: string,
      image: string,
      shopId: BigNumberish,
      governor: string,
      overrides?: CallOverrides
    ): Promise<string>;

    setShopTemplate(
      _shopTemplate: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    createShop(
      owner: string,
      name: string,
      image: string,
      shopId: BigNumberish,
      governor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setShopTemplate(
      _shopTemplate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createShop(
      owner: string,
      name: string,
      image: string,
      shopId: BigNumberish,
      governor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setShopTemplate(
      _shopTemplate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
