/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ShopMakerInterfaceInterface extends utils.Interface {
  contractName: "ShopMakerInterface";
  functions: {
    "createShop(address,string,string,string,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createShop",
    values: [string, string, string, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "createShop", data: BytesLike): Result;

  events: {};
}

export interface ShopMakerInterface extends BaseContract {
  contractName: "ShopMakerInterface";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ShopMakerInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createShop(
      owner: string,
      name: string,
      description: string,
      location: string,
      phone: string,
      image: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createShop(
    owner: string,
    name: string,
    description: string,
    location: string,
    phone: string,
    image: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createShop(
      owner: string,
      name: string,
      description: string,
      location: string,
      phone: string,
      image: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createShop(
      owner: string,
      name: string,
      description: string,
      location: string,
      phone: string,
      image: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createShop(
      owner: string,
      name: string,
      description: string,
      location: string,
      phone: string,
      image: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
