/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ShopMakerInterface extends utils.Interface {
  contractName: "ShopMaker";
  functions: {
    "createShop(address,string,string,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createShop",
    values: [string, string, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "createShop", data: BytesLike): Result;

  events: {
    "ShopCreated(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ShopCreated"): EventFragment;
}

export type ShopCreatedEvent = TypedEvent<
  [string, string],
  { shopAddress: string; name: string }
>;

export type ShopCreatedEventFilter = TypedEventFilter<ShopCreatedEvent>;

export interface ShopMaker extends BaseContract {
  contractName: "ShopMaker";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ShopMakerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createShop(
      _owner: string,
      _name: string,
      _image: string,
      _shopId: BigNumberish,
      _governor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createShop(
    _owner: string,
    _name: string,
    _image: string,
    _shopId: BigNumberish,
    _governor: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createShop(
      _owner: string,
      _name: string,
      _image: string,
      _shopId: BigNumberish,
      _governor: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "ShopCreated(address,string)"(
      shopAddress?: string | null,
      name?: string | null
    ): ShopCreatedEventFilter;
    ShopCreated(
      shopAddress?: string | null,
      name?: string | null
    ): ShopCreatedEventFilter;
  };

  estimateGas: {
    createShop(
      _owner: string,
      _name: string,
      _image: string,
      _shopId: BigNumberish,
      _governor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createShop(
      _owner: string,
      _name: string,
      _image: string,
      _shopId: BigNumberish,
      _governor: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
