/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace Shop {
  export type ItemStruct = {
    itemId: BigNumberish;
    name: string;
    description: string;
    image: string;
    price: BigNumberish;
    inStock: boolean;
  };

  export type ItemStructOutput = [
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    boolean
  ] & {
    itemId: BigNumber;
    name: string;
    description: string;
    image: string;
    price: BigNumber;
    inStock: boolean;
  };

  export type TransStruct = {
    transId: BigNumberish;
    itemIds: BigNumberish[];
    itemQty: BigNumberish[];
    total: BigNumberish;
    isValid: boolean;
  };

  export type TransStructOutput = [
    BigNumber,
    BigNumber[],
    BigNumber[],
    BigNumber,
    boolean
  ] & {
    transId: BigNumber;
    itemIds: BigNumber[];
    itemQty: BigNumber[];
    total: BigNumber;
    isValid: boolean;
  };
}

export interface ShopInterface extends utils.Interface {
  contractName: "Shop";
  functions: {
    "catalog(uint256)": FunctionFragment;
    "createItem(string,string,string,uint256)": FunctionFragment;
    "description()": FunctionFragment;
    "fetchCatalogItems()": FunctionFragment;
    "fetchTransactions()": FunctionFragment;
    "image()": FunctionFragment;
    "location()": FunctionFragment;
    "makeTransaction(uint256[],uint256[])": FunctionFragment;
    "name()": FunctionFragment;
    "owner()": FunctionFragment;
    "phone()": FunctionFragment;
    "transactions(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "catalog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createItem",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchCatalogItems",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "image", values?: undefined): string;
  encodeFunctionData(functionFragment: "location", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "makeTransaction",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "phone", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "catalog", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createItem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchCatalogItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "image", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "location", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "makeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "phone", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;

  events: {
    "ItemCreated(uint256,string,string,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ItemCreated"): EventFragment;
}

export type ItemCreatedEvent = TypedEvent<
  [BigNumber, string, string, string, BigNumber],
  {
    itemId: BigNumber;
    name: string;
    description: string;
    image: string;
    price: BigNumber;
  }
>;

export type ItemCreatedEventFilter = TypedEventFilter<ItemCreatedEvent>;

export interface Shop extends BaseContract {
  contractName: "Shop";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ShopInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    catalog(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, string, BigNumber, boolean] & {
        itemId: BigNumber;
        name: string;
        description: string;
        image: string;
        price: BigNumber;
        inStock: boolean;
      }
    >;

    createItem(
      name: string,
      description: string,
      image: string,
      price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    description(overrides?: CallOverrides): Promise<[string]>;

    fetchCatalogItems(
      overrides?: CallOverrides
    ): Promise<[Shop.ItemStructOutput[]]>;

    fetchTransactions(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    image(overrides?: CallOverrides): Promise<[string]>;

    location(overrides?: CallOverrides): Promise<[string]>;

    makeTransaction(
      itemIds: BigNumberish[],
      itemQty: BigNumberish[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    phone(overrides?: CallOverrides): Promise<[string]>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        transId: BigNumber;
        total: BigNumber;
        isValid: boolean;
      }
    >;
  };

  catalog(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, string, BigNumber, boolean] & {
      itemId: BigNumber;
      name: string;
      description: string;
      image: string;
      price: BigNumber;
      inStock: boolean;
    }
  >;

  createItem(
    name: string,
    description: string,
    image: string,
    price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  description(overrides?: CallOverrides): Promise<string>;

  fetchCatalogItems(
    overrides?: CallOverrides
  ): Promise<Shop.ItemStructOutput[]>;

  fetchTransactions(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  image(overrides?: CallOverrides): Promise<string>;

  location(overrides?: CallOverrides): Promise<string>;

  makeTransaction(
    itemIds: BigNumberish[],
    itemQty: BigNumberish[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  phone(overrides?: CallOverrides): Promise<string>;

  transactions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean] & {
      transId: BigNumber;
      total: BigNumber;
      isValid: boolean;
    }
  >;

  callStatic: {
    catalog(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, string, BigNumber, boolean] & {
        itemId: BigNumber;
        name: string;
        description: string;
        image: string;
        price: BigNumber;
        inStock: boolean;
      }
    >;

    createItem(
      name: string,
      description: string,
      image: string,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    description(overrides?: CallOverrides): Promise<string>;

    fetchCatalogItems(
      overrides?: CallOverrides
    ): Promise<Shop.ItemStructOutput[]>;

    fetchTransactions(
      overrides?: CallOverrides
    ): Promise<Shop.TransStructOutput[]>;

    image(overrides?: CallOverrides): Promise<string>;

    location(overrides?: CallOverrides): Promise<string>;

    makeTransaction(
      itemIds: BigNumberish[],
      itemQty: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    phone(overrides?: CallOverrides): Promise<string>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        transId: BigNumber;
        total: BigNumber;
        isValid: boolean;
      }
    >;
  };

  filters: {
    "ItemCreated(uint256,string,string,string,uint256)"(
      itemId?: null,
      name?: null,
      description?: null,
      image?: null,
      price?: null
    ): ItemCreatedEventFilter;
    ItemCreated(
      itemId?: null,
      name?: null,
      description?: null,
      image?: null,
      price?: null
    ): ItemCreatedEventFilter;
  };

  estimateGas: {
    catalog(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    createItem(
      name: string,
      description: string,
      image: string,
      price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    description(overrides?: CallOverrides): Promise<BigNumber>;

    fetchCatalogItems(overrides?: CallOverrides): Promise<BigNumber>;

    fetchTransactions(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    image(overrides?: CallOverrides): Promise<BigNumber>;

    location(overrides?: CallOverrides): Promise<BigNumber>;

    makeTransaction(
      itemIds: BigNumberish[],
      itemQty: BigNumberish[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    phone(overrides?: CallOverrides): Promise<BigNumber>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    catalog(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createItem(
      name: string,
      description: string,
      image: string,
      price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    description(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fetchCatalogItems(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fetchTransactions(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    image(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    location(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    makeTransaction(
      itemIds: BigNumberish[],
      itemQty: BigNumberish[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    phone(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transactions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
